/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MecanicoRouteImport } from './routes/mecanico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImplantadorRouteImport } from './routes/implantador'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MecanicoIndexRouteImport } from './routes/mecanico.index'
import { Route as ImplantadorIndexRouteImport } from './routes/implantador.index'
import { Route as MecanicoHistoricoRouteImport } from './routes/mecanico.historico'
import { Route as ImplantadorMaquinasRouteImport } from './routes/implantador.maquinas'
import { Route as ImplantadorReferenciasMachineIdRouteImport } from './routes/implantador.referencias.$machineId'
import { Route as ApiPublicMorningTriggerRouteImport } from './routes/api.public.morning-trigger'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api.public.whatsapp.webhook'
import { Route as ApiPublicDiagEnvRouteImport } from './routes/api.public.diag.env'

const MecanicoRoute = MecanicoRouteImport.update({
  id: '/mecanico',
  path: '/mecanico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantadorRoute = ImplantadorRouteImport.update({
  id: '/implantador',
  path: '/implantador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MecanicoIndexRoute = MecanicoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MecanicoRoute,
} as any)
const ImplantadorIndexRoute = ImplantadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImplantadorRoute,
} as any)
const MecanicoHistoricoRoute = MecanicoHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => MecanicoRoute,
} as any)
const ImplantadorMaquinasRoute = ImplantadorMaquinasRouteImport.update({
  id: '/maquinas',
  path: '/maquinas',
  getParentRoute: () => ImplantadorRoute,
} as any)
const ImplantadorReferenciasMachineIdRoute =
  ImplantadorReferenciasMachineIdRouteImport.update({
    id: '/referencias/$machineId',
    path: '/referencias/$machineId',
    getParentRoute: () => ImplantadorRoute,
  } as any)
const ApiPublicMorningTriggerRoute = ApiPublicMorningTriggerRouteImport.update({
  id: '/api/public/morning-trigger',
  path: '/api/public/morning-trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagEnvRoute = ApiPublicDiagEnvRouteImport.update({
  id: '/api/public/diag/env',
  path: '/api/public/diag/env',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/implantador': typeof ImplantadorRouteWithChildren
  '/login': typeof LoginRoute
  '/mecanico': typeof MecanicoRouteWithChildren
  '/implantador/maquinas': typeof ImplantadorMaquinasRoute
  '/mecanico/historico': typeof MecanicoHistoricoRoute
  '/implantador/': typeof ImplantadorIndexRoute
  '/mecanico/': typeof MecanicoIndexRoute
  '/api/public/morning-trigger': typeof ApiPublicMorningTriggerRoute
  '/implantador/referencias/$machineId': typeof ImplantadorReferenciasMachineIdRoute
  '/api/public/diag/env': typeof ApiPublicDiagEnvRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/implantador/maquinas': typeof ImplantadorMaquinasRoute
  '/mecanico/historico': typeof MecanicoHistoricoRoute
  '/implantador': typeof ImplantadorIndexRoute
  '/mecanico': typeof MecanicoIndexRoute
  '/api/public/morning-trigger': typeof ApiPublicMorningTriggerRoute
  '/implantador/referencias/$machineId': typeof ImplantadorReferenciasMachineIdRoute
  '/api/public/diag/env': typeof ApiPublicDiagEnvRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/implantador': typeof ImplantadorRouteWithChildren
  '/login': typeof LoginRoute
  '/mecanico': typeof MecanicoRouteWithChildren
  '/implantador/maquinas': typeof ImplantadorMaquinasRoute
  '/mecanico/historico': typeof MecanicoHistoricoRoute
  '/implantador/': typeof ImplantadorIndexRoute
  '/mecanico/': typeof MecanicoIndexRoute
  '/api/public/morning-trigger': typeof ApiPublicMorningTriggerRoute
  '/implantador/referencias/$machineId': typeof ImplantadorReferenciasMachineIdRoute
  '/api/public/diag/env': typeof ApiPublicDiagEnvRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/implantador'
    | '/login'
    | '/mecanico'
    | '/implantador/maquinas'
    | '/mecanico/historico'
    | '/implantador/'
    | '/mecanico/'
    | '/api/public/morning-trigger'
    | '/implantador/referencias/$machineId'
    | '/api/public/diag/env'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/implantador/maquinas'
    | '/mecanico/historico'
    | '/implantador'
    | '/mecanico'
    | '/api/public/morning-trigger'
    | '/implantador/referencias/$machineId'
    | '/api/public/diag/env'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/implantador'
    | '/login'
    | '/mecanico'
    | '/implantador/maquinas'
    | '/mecanico/historico'
    | '/implantador/'
    | '/mecanico/'
    | '/api/public/morning-trigger'
    | '/implantador/referencias/$machineId'
    | '/api/public/diag/env'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ImplantadorRoute: typeof ImplantadorRouteWithChildren
  LoginRoute: typeof LoginRoute
  MecanicoRoute: typeof MecanicoRouteWithChildren
  ApiPublicMorningTriggerRoute: typeof ApiPublicMorningTriggerRoute
  ApiPublicDiagEnvRoute: typeof ApiPublicDiagEnvRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mecanico': {
      id: '/mecanico'
      path: '/mecanico'
      fullPath: '/mecanico'
      preLoaderRoute: typeof MecanicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implantador': {
      id: '/implantador'
      path: '/implantador'
      fullPath: '/implantador'
      preLoaderRoute: typeof ImplantadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mecanico/': {
      id: '/mecanico/'
      path: '/'
      fullPath: '/mecanico/'
      preLoaderRoute: typeof MecanicoIndexRouteImport
      parentRoute: typeof MecanicoRoute
    }
    '/implantador/': {
      id: '/implantador/'
      path: '/'
      fullPath: '/implantador/'
      preLoaderRoute: typeof ImplantadorIndexRouteImport
      parentRoute: typeof ImplantadorRoute
    }
    '/mecanico/historico': {
      id: '/mecanico/historico'
      path: '/historico'
      fullPath: '/mecanico/historico'
      preLoaderRoute: typeof MecanicoHistoricoRouteImport
      parentRoute: typeof MecanicoRoute
    }
    '/implantador/maquinas': {
      id: '/implantador/maquinas'
      path: '/maquinas'
      fullPath: '/implantador/maquinas'
      preLoaderRoute: typeof ImplantadorMaquinasRouteImport
      parentRoute: typeof ImplantadorRoute
    }
    '/implantador/referencias/$machineId': {
      id: '/implantador/referencias/$machineId'
      path: '/referencias/$machineId'
      fullPath: '/implantador/referencias/$machineId'
      preLoaderRoute: typeof ImplantadorReferenciasMachineIdRouteImport
      parentRoute: typeof ImplantadorRoute
    }
    '/api/public/morning-trigger': {
      id: '/api/public/morning-trigger'
      path: '/api/public/morning-trigger'
      fullPath: '/api/public/morning-trigger'
      preLoaderRoute: typeof ApiPublicMorningTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag/env': {
      id: '/api/public/diag/env'
      path: '/api/public/diag/env'
      fullPath: '/api/public/diag/env'
      preLoaderRoute: typeof ApiPublicDiagEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ImplantadorRouteChildren {
  ImplantadorMaquinasRoute: typeof ImplantadorMaquinasRoute
  ImplantadorIndexRoute: typeof ImplantadorIndexRoute
  ImplantadorReferenciasMachineIdRoute: typeof ImplantadorReferenciasMachineIdRoute
}

const ImplantadorRouteChildren: ImplantadorRouteChildren = {
  ImplantadorMaquinasRoute: ImplantadorMaquinasRoute,
  ImplantadorIndexRoute: ImplantadorIndexRoute,
  ImplantadorReferenciasMachineIdRoute: ImplantadorReferenciasMachineIdRoute,
}

const ImplantadorRouteWithChildren = ImplantadorRoute._addFileChildren(
  ImplantadorRouteChildren,
)

interface MecanicoRouteChildren {
  MecanicoHistoricoRoute: typeof MecanicoHistoricoRoute
  MecanicoIndexRoute: typeof MecanicoIndexRoute
}

const MecanicoRouteChildren: MecanicoRouteChildren = {
  MecanicoHistoricoRoute: MecanicoHistoricoRoute,
  MecanicoIndexRoute: MecanicoIndexRoute,
}

const MecanicoRouteWithChildren = MecanicoRoute._addFileChildren(
  MecanicoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ImplantadorRoute: ImplantadorRouteWithChildren,
  LoginRoute: LoginRoute,
  MecanicoRoute: MecanicoRouteWithChildren,
  ApiPublicMorningTriggerRoute: ApiPublicMorningTriggerRoute,
  ApiPublicDiagEnvRoute: ApiPublicDiagEnvRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
