/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MecanicoRouteImport } from './routes/mecanico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImplantadorRouteImport } from './routes/implantador'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImplantadorIndexRouteImport } from './routes/implantador.index'
import { Route as ImplantadorMaquinasRouteImport } from './routes/implantador.maquinas'
import { Route as ImplantadorReferenciasMachineIdRouteImport } from './routes/implantador.referencias.$machineId'

const MecanicoRoute = MecanicoRouteImport.update({
  id: '/mecanico',
  path: '/mecanico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantadorRoute = ImplantadorRouteImport.update({
  id: '/implantador',
  path: '/implantador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantadorIndexRoute = ImplantadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImplantadorRoute,
} as any)
const ImplantadorMaquinasRoute = ImplantadorMaquinasRouteImport.update({
  id: '/maquinas',
  path: '/maquinas',
  getParentRoute: () => ImplantadorRoute,
} as any)
const ImplantadorReferenciasMachineIdRoute =
  ImplantadorReferenciasMachineIdRouteImport.update({
    id: '/referencias/$machineId',
    path: '/referencias/$machineId',
    getParentRoute: () => ImplantadorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/implantador': typeof ImplantadorRouteWithChildren
  '/login': typeof LoginRoute
  '/mecanico': typeof MecanicoRoute
  '/implantador/maquinas': typeof ImplantadorMaquinasRoute
  '/implantador/': typeof ImplantadorIndexRoute
  '/implantador/referencias/$machineId': typeof ImplantadorReferenciasMachineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/mecanico': typeof MecanicoRoute
  '/implantador/maquinas': typeof ImplantadorMaquinasRoute
  '/implantador': typeof ImplantadorIndexRoute
  '/implantador/referencias/$machineId': typeof ImplantadorReferenciasMachineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/implantador': typeof ImplantadorRouteWithChildren
  '/login': typeof LoginRoute
  '/mecanico': typeof MecanicoRoute
  '/implantador/maquinas': typeof ImplantadorMaquinasRoute
  '/implantador/': typeof ImplantadorIndexRoute
  '/implantador/referencias/$machineId': typeof ImplantadorReferenciasMachineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/implantador'
    | '/login'
    | '/mecanico'
    | '/implantador/maquinas'
    | '/implantador/'
    | '/implantador/referencias/$machineId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/mecanico'
    | '/implantador/maquinas'
    | '/implantador'
    | '/implantador/referencias/$machineId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/implantador'
    | '/login'
    | '/mecanico'
    | '/implantador/maquinas'
    | '/implantador/'
    | '/implantador/referencias/$machineId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ImplantadorRoute: typeof ImplantadorRouteWithChildren
  LoginRoute: typeof LoginRoute
  MecanicoRoute: typeof MecanicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mecanico': {
      id: '/mecanico'
      path: '/mecanico'
      fullPath: '/mecanico'
      preLoaderRoute: typeof MecanicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implantador': {
      id: '/implantador'
      path: '/implantador'
      fullPath: '/implantador'
      preLoaderRoute: typeof ImplantadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implantador/': {
      id: '/implantador/'
      path: '/'
      fullPath: '/implantador/'
      preLoaderRoute: typeof ImplantadorIndexRouteImport
      parentRoute: typeof ImplantadorRoute
    }
    '/implantador/maquinas': {
      id: '/implantador/maquinas'
      path: '/maquinas'
      fullPath: '/implantador/maquinas'
      preLoaderRoute: typeof ImplantadorMaquinasRouteImport
      parentRoute: typeof ImplantadorRoute
    }
    '/implantador/referencias/$machineId': {
      id: '/implantador/referencias/$machineId'
      path: '/referencias/$machineId'
      fullPath: '/implantador/referencias/$machineId'
      preLoaderRoute: typeof ImplantadorReferenciasMachineIdRouteImport
      parentRoute: typeof ImplantadorRoute
    }
  }
}

interface ImplantadorRouteChildren {
  ImplantadorMaquinasRoute: typeof ImplantadorMaquinasRoute
  ImplantadorIndexRoute: typeof ImplantadorIndexRoute
  ImplantadorReferenciasMachineIdRoute: typeof ImplantadorReferenciasMachineIdRoute
}

const ImplantadorRouteChildren: ImplantadorRouteChildren = {
  ImplantadorMaquinasRoute: ImplantadorMaquinasRoute,
  ImplantadorIndexRoute: ImplantadorIndexRoute,
  ImplantadorReferenciasMachineIdRoute: ImplantadorReferenciasMachineIdRoute,
}

const ImplantadorRouteWithChildren = ImplantadorRoute._addFileChildren(
  ImplantadorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ImplantadorRoute: ImplantadorRouteWithChildren,
  LoginRoute: LoginRoute,
  MecanicoRoute: MecanicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
