// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctzajxycetufjkpqhidz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0emFqeHljZXR1ZmprcHFoaWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5NjI2MDIsImV4cCI6MjA5MjUzODYwMn0.YtFAvjZon0Z1Y5ZFXMg8JTmQpdak8_7dGwVz9ty4AZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});